### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by camillethuyentruong** [abelardoacm/ssDNA_viral_pangenomics#6]
**10% Organización del repositorio**
Folders need to be added for figures and results, with short descriptions in the general README

**15% README (debe ser en inglés)**
Your pipeline is very long and detailed, well done! I suggest moving the section describing the scripts to a new README in bin, leaving the pipeline figure in the general README.

Names sometimes don't correspond exactly, for example **Expected Raw_database** (in README) corresponds to the folder data/Raw_database. It can be confusing! You could also add direct links in the README (as you did for scripts) to help the reader find its way. 

Other folders you are describing are missing, for example **Proteomic fasta** and **Individual genbank files**. If these are data in progress, this need to be mentioned in the README (same for the result folder, currently missing). 

**15% Análisis**
Complex and innovative, well done!

**15% Resumen y discusión en formato Markdown**
Missing so far

**15% Gráfica(s) en R**
Missing so far

**15% Scripts deben estar comentados en inglés**
In [`3_Protein_count_filtering.pl`](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/bin/3_Protein_count_filtering.pl) is there any reason to copy the data files to a new folder at the beginning instead of working directly with them? If you have large dataset, copying them increase the memory needed to run the analyses.

In [`4_Vectors_CPFSCC.sh`](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/bin/4_Vectors_CPFSCC.sh) you can combine all characters to remove in a single command:
`sed -i 's/[\,;:]/-/g' ../data/AF_methods_input/$1_AF_input.fasta`

**15% Avances, organización y respuesta a comentarios en el proyecto de Github en inglés**
One issue is still open and need to be at least commented.

**Comment by abelardoacm** [comment]
thanks a lot !!,

I'll work on it as soon as possible :computer:

**Comment by abelardoacm** [comment]
Accepted and carried out suggestions:

- :heavy_check_mark: Added folders for figures and results
- :heavy_check_mark:  New README in bin
- :heavy_check_mark: Files with proper names and links
- :heavy_check_mark: All files mentioned are now available
- :heavy_check_mark: All special characters are removed by a single line in 4_Vectors_CPFSCC.sh
- :heavy_check_mark: I've updated and commented my advances in opened issue... which seems to be willing to stay for a while longer
- :heavy_check_mark: R graphs were generated long ago, however I haven't noticed that they can't be seen online because of the size. I've just committed some sample graphs to show in an upcoming md summary and discussion.
- :heavy_check_mark:  [Resumen y discusión en formato Markdown](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/ABriefRepoHistory.md)


Pending:
- :hourglass_flowing_sand: In 3_Protein_count_filtering.pl the only reasons are bad programming practices. I haven't noticed runtime increase even with a db containing all viral genomes in refseq, however I'm aware that this should be corrected so I'm going to include it in my project [Replace choco scripts with real ones](https://github.com/abelardoacm/ssDNA_viral_pangenomics/projects/3), which is all about improving my programing practices.

**Comment by abelardoacm** [comment]
:heavy_check_mark:  DONE, also I made [ABriefRepoHistory.md](https://github.com/abelardoacm/ssDNA_viral_pangenomics/blob/main/ABriefRepoHistory.md), and a new [README.md](https://github.com/abelardoacm/ssDNA_viral_pangenomics/tree/main/bin) merely for bin.

**Comment by camillethuyentruong** [comment]
I enjoyed reading your repo history a lot and your script animations are really cool! Have you ever though about writing a blog? :)
Seriously, your script and repo are well-documented and much clearer now - congratulations!

I hope you enjoyed the course.

**Comment by abelardoacm** [comment]
@camillethuyentruong thank you very much !! I really enjoy writing about my work in a "not ultra serious" way and maybe I cand find the time to share it. The course was great, it felt like being with friends to share and discuss if possible I'd like to enroll in the upcoming editions in a way to help with certain topics where I have practice or even help with issues sessions. 

Once again thanks a lot !!!
